### ISSUE TITLE
No supported Vault instance found at the this URL

### ISSUE THREAD

**Issue by danielhass** [adobe/cryptr#30] opened 2018-04-20 07:01 UTC
## The problem

Error trying to connect to Vault 0.10.0 Cluster.

## Environment

* Cryptr version (or git revision) that exhibits the issue: 0.2.0
* Desktop OS/version used to run Cryptr: Windows 10 & Debian 9
* Vault version: 0.10.0

## Details

I tried to connect to a Vault HA Cluster via Cryptr. After entering the URL a error notification (toast like message) pops up that says: "No supported Vault instance found at the this URL".

As Connection endpoint I'm using the Vault Active Node Address: `https://X.X.X.X:8200`

## Steps to Reproduce

- Start Cryptr
- Enter connection details
- Error shows up

**Comment by jcrowthe** [comment] 2018-04-25 01:49
@danielhass I've confirmed that Cryptr still functions with 0.10.0 release of Vault. However, support for the newly released versioned k/v backend is not yet supported in Cryptr.

In regard to your issue, I have been unable to reproduce this as of yet. Can you confirm that you can connect to a dev server running on your local machine?

**Comment by danielhass** [comment] 2018-04-26 06:29
@jcrowthe thanks for your reply! I was able to connect against a local vault instance in dev mode version 0.10.0. But there I wasn't able to create any secrets (error message: _An error occurred while updating this secret. Check permissions?_ ). Afterwards I started a local dev vault server v0.9.6 and there everything works fine...

**Comment by danielhass** [comment] 2018-05-01 08:12
@jcrowthe yes the error keeps showing up, even after I selected a different URL.

Is it possible to start Cryptr in some kind of a debug modus? A little more verbose output on the cli for instance?

**Comment by jcrowthe** [comment] 2018-05-01 16:43
@danielhass Yes, two ways to do so. If you have the code checked out, you can run `npm run dev`, or if you are using a binary release you can run `CRYPTR_ENV=development open /Applications/Cryptr.app` on a mac. These will open the Chrome Developer Tools allowing you full debug ability.

**Comment by danielhass** [comment] 2018-05-15 06:52
@jcrowthe sorry that it took me so long to come back to this one. With the development environment set I was able to find the cause of the error. It was our internally signed ssl cert. Cryptr/Electron doesn't seem to use the OS cert store to gain trust with CAs. Is there a way to add custom CAs?

I was able to see all the k/v version 1 backends. Are you planning to support version 2? Even without full support for versions, maybe only displaying the most recent one (like the offical vault ui does)?

**Comment by xelite** [comment] 2018-12-24 13:32
I got same issue with self-signed CA. Please add posibility to add custom ca certs.
![cert-error](https://user-images.githubusercontent.com/5921448/50400660-c4c98a80-0788-11e9-8e9f-01bbe0d4ce6b.png)

**Comment by danielhass** [comment] 2018-12-30 09:37
@jcrowthe thanks for your detailed answer! My use case exactly falls into case 2 but when I tested this a while ago it doesn't seem to work for me. I totally agree with you that you need to keep the bar high due to the critical role of TLS during secret access via Cryptr.

After new years eve I will dive into testing once more and see if the OS cert store is used properly in our setup. I will test this on Windows and Debian Linux. I will post feedback here as soon as the testing is done.

Regarding v2 backends: great to hear that you're planning to support this! I'm happy to see that Cryptr is still under development as it is my favorite Vault UI for quick access to secrets, mainly because of the "fuzzy search" feature.

**Comment by danielhass** [comment] 2019-01-02 10:06
@jcrowthe I can confirm that Cryptr is using ths OS cert store correctly on Windows 10 and 7. The issue still persists on my machine but I tested the setup on serveral machines form co-workers and there it's working out of the box. So there seems to something wrong with my machine only.

Under Debian 9 Chromium and therefore Electron is not using the OS cert store under `/usr/local/share/ca-certificates/`. I had to import the internal CA via the chromium installation on that machine (Settings->Certificates->Authorities->Import). Afterwards also Cryptr stopped complaining about insecure requests.

I think you can close this one know. Thanks for your support!

**Comment by jcrowthe** [comment] 2019-01-02 17:54
@danielhass Thanks for putting in the time to test! Good find with Debian as well. I'll go ahead and close this.

**Closed by jcrowthe** 2019-01-02 17:54 UTC
